//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameRoomWeb.CameRoomService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CameRoomService.IService")]
    public interface IService {
        
        // CODEGEN: Parameter 'GetDataResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CameRoomWeb.CameRoomService.GetDataResponse GetData(CameRoomWeb.CameRoomService.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.GetDataResponse> GetDataAsync(CameRoomWeb.CameRoomService.GetDataRequest request);
        
        // CODEGEN: Parameter 'GetDataUsingDataContractResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CameRoomWeb.CameRoomService.GetDataUsingDataContractResponse GetDataUsingDataContract(CameRoomWeb.CameRoomService.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(CameRoomWeb.CameRoomService.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getProvinceList", ReplyAction="http://tempuri.org/IService/getProvinceListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CameRoomWeb.CameRoomService.getProvinceListResponse getProvinceList(CameRoomWeb.CameRoomService.getProvinceListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getProvinceList", ReplyAction="http://tempuri.org/IService/getProvinceListResponse")]
        System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.getProvinceListResponse> getProvinceListAsync(CameRoomWeb.CameRoomService.getProvinceListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getPlaceListByProvinceID", ReplyAction="http://tempuri.org/IService/getPlaceListByProvinceIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CameRoomWeb.CameRoomService.getPlaceListByProvinceIDResponse getPlaceListByProvinceID(CameRoomWeb.CameRoomService.getPlaceListByProvinceIDRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getPlaceListByProvinceID", ReplyAction="http://tempuri.org/IService/getPlaceListByProvinceIDResponse")]
        System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.getPlaceListByProvinceIDResponse> getPlaceListByProvinceIDAsync(CameRoomWeb.CameRoomService.getPlaceListByProvinceIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insertGrapherRegister", ReplyAction="http://tempuri.org/IService/insertGrapherRegisterResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CameRoomWeb.CameRoomService.insertGrapherRegisterResponse insertGrapherRegister(CameRoomWeb.CameRoomService.insertGrapherRegisterRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insertGrapherRegister", ReplyAction="http://tempuri.org/IService/insertGrapherRegisterResponse")]
        System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.insertGrapherRegisterResponse> insertGrapherRegisterAsync(CameRoomWeb.CameRoomService.insertGrapherRegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insertGrapherRegisterMapEarningRate", ReplyAction="http://tempuri.org/IService/insertGrapherRegisterMapEarningRateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CameRoomWeb.CameRoomService.insertGrapherRegisterMapEarningRateResponse insertGrapherRegisterMapEarningRate(CameRoomWeb.CameRoomService.insertGrapherRegisterMapEarningRateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insertGrapherRegisterMapEarningRate", ReplyAction="http://tempuri.org/IService/insertGrapherRegisterMapEarningRateResponse")]
        System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.insertGrapherRegisterMapEarningRateResponse> insertGrapherRegisterMapEarningRateAsync(CameRoomWeb.CameRoomService.insertGrapherRegisterMapEarningRateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getGrapherProfileByEmail", ReplyAction="http://tempuri.org/IService/getGrapherProfileByEmailResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CameRoomWeb.CameRoomService.getGrapherProfileByEmailResponse getGrapherProfileByEmail(CameRoomWeb.CameRoomService.getGrapherProfileByEmailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getGrapherProfileByEmail", ReplyAction="http://tempuri.org/IService/getGrapherProfileByEmailResponse")]
        System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.getGrapherProfileByEmailResponse> getGrapherProfileByEmailAsync(CameRoomWeb.CameRoomService.getGrapherProfileByEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getGrapherEarningRateProfileByGrapherIDandGrapherEmai" +
            "l", ReplyAction="http://tempuri.org/IService/getGrapherEarningRateProfileByGrapherIDandGrapherEmai" +
            "lResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CameRoomWeb.CameRoomService.getGrapherEarningRateProfileByGrapherIDandGrapherEmailResponse getGrapherEarningRateProfileByGrapherIDandGrapherEmail(CameRoomWeb.CameRoomService.getGrapherEarningRateProfileByGrapherIDandGrapherEmailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getGrapherEarningRateProfileByGrapherIDandGrapherEmai" +
            "l", ReplyAction="http://tempuri.org/IService/getGrapherEarningRateProfileByGrapherIDandGrapherEmai" +
            "lResponse")]
        System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.getGrapherEarningRateProfileByGrapherIDandGrapherEmailResponse> getGrapherEarningRateProfileByGrapherIDandGrapherEmailAsync(CameRoomWeb.CameRoomService.getGrapherEarningRateProfileByGrapherIDandGrapherEmailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int value;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(int value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetDataResult;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(string GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CompositeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
                this.RaisePropertyChanged("BoolValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
                this.RaisePropertyChanged("BoolValueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
                this.RaisePropertyChanged("StringValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CameRoomWeb.CameRoomService.CompositeType composite;
        
        public GetDataUsingDataContractRequest() {
        }
        
        public GetDataUsingDataContractRequest(CameRoomWeb.CameRoomService.CompositeType composite) {
            this.composite = composite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContractResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CameRoomWeb.CameRoomService.CompositeType GetDataUsingDataContractResult;
        
        public GetDataUsingDataContractResponse() {
        }
        
        public GetDataUsingDataContractResponse(CameRoomWeb.CameRoomService.CompositeType GetDataUsingDataContractResult) {
            this.GetDataUsingDataContractResult = GetDataUsingDataContractResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProvinceList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getProvinceListRequest {
        
        public getProvinceListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProvinceListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getProvinceListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool getProvinceListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet ds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errMsg;
        
        public getProvinceListResponse() {
        }
        
        public getProvinceListResponse(bool getProvinceListResult, System.Data.DataSet ds, string errMsg) {
            this.getProvinceListResult = getProvinceListResult;
            this.ds = ds;
            this.errMsg = errMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPlaceListByProvinceID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getPlaceListByProvinceIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int provinceID;
        
        public getPlaceListByProvinceIDRequest() {
        }
        
        public getPlaceListByProvinceIDRequest(int provinceID) {
            this.provinceID = provinceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPlaceListByProvinceIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getPlaceListByProvinceIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool getPlaceListByProvinceIDResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet ds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errMsg;
        
        public getPlaceListByProvinceIDResponse() {
        }
        
        public getPlaceListByProvinceIDResponse(bool getPlaceListByProvinceIDResult, System.Data.DataSet ds, string errMsg) {
            this.getPlaceListByProvinceIDResult = getPlaceListByProvinceIDResult;
            this.ds = ds;
            this.errMsg = errMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertGrapherRegister", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class insertGrapherRegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GrapherEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GrapherName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GrapherSurname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GrapherPersonalID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] GrapherPhoto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GrapherMobileNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GrapherSex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public int ProvinceID;
        
        public insertGrapherRegisterRequest() {
        }
        
        public insertGrapherRegisterRequest(string GrapherEmail, string GrapherName, string GrapherSurname, string GrapherPersonalID, byte[] GrapherPhoto, string GrapherMobileNumber, string GrapherSex, string Password, int ProvinceID) {
            this.GrapherEmail = GrapherEmail;
            this.GrapherName = GrapherName;
            this.GrapherSurname = GrapherSurname;
            this.GrapherPersonalID = GrapherPersonalID;
            this.GrapherPhoto = GrapherPhoto;
            this.GrapherMobileNumber = GrapherMobileNumber;
            this.GrapherSex = GrapherSex;
            this.Password = Password;
            this.ProvinceID = ProvinceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertGrapherRegisterResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class insertGrapherRegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool insertGrapherRegisterResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public long GrapherID;
        
        public insertGrapherRegisterResponse() {
        }
        
        public insertGrapherRegisterResponse(bool insertGrapherRegisterResult, string errMsg, long GrapherID) {
            this.insertGrapherRegisterResult = insertGrapherRegisterResult;
            this.errMsg = errMsg;
            this.GrapherID = GrapherID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertGrapherRegisterMapEarningRate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class insertGrapherRegisterMapEarningRateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long GrapherID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int EventTypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public double MorningRate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public double AfternoonRate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public double EveningRate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public double FullDayRate;
        
        public insertGrapherRegisterMapEarningRateRequest() {
        }
        
        public insertGrapherRegisterMapEarningRateRequest(long GrapherID, int EventTypeID, double MorningRate, double AfternoonRate, double EveningRate, double FullDayRate) {
            this.GrapherID = GrapherID;
            this.EventTypeID = EventTypeID;
            this.MorningRate = MorningRate;
            this.AfternoonRate = AfternoonRate;
            this.EveningRate = EveningRate;
            this.FullDayRate = FullDayRate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertGrapherRegisterMapEarningRateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class insertGrapherRegisterMapEarningRateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool insertGrapherRegisterMapEarningRateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errMsg;
        
        public insertGrapherRegisterMapEarningRateResponse() {
        }
        
        public insertGrapherRegisterMapEarningRateResponse(bool insertGrapherRegisterMapEarningRateResult, string errMsg) {
            this.insertGrapherRegisterMapEarningRateResult = insertGrapherRegisterMapEarningRateResult;
            this.errMsg = errMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGrapherProfileByEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getGrapherProfileByEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GrapherEmail;
        
        public getGrapherProfileByEmailRequest() {
        }
        
        public getGrapherProfileByEmailRequest(string GrapherEmail) {
            this.GrapherEmail = GrapherEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGrapherProfileByEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getGrapherProfileByEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool getGrapherProfileByEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public long GrapherID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GrapherName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GrapherSurname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GrapherPersonalID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GrapherMobileNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GrapherSex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public int ProvinceID;
        
        public getGrapherProfileByEmailResponse() {
        }
        
        public getGrapherProfileByEmailResponse(bool getGrapherProfileByEmailResult, string errMsg, long GrapherID, string GrapherName, string GrapherSurname, string GrapherPersonalID, string GrapherMobileNumber, string GrapherSex, int ProvinceID) {
            this.getGrapherProfileByEmailResult = getGrapherProfileByEmailResult;
            this.errMsg = errMsg;
            this.GrapherID = GrapherID;
            this.GrapherName = GrapherName;
            this.GrapherSurname = GrapherSurname;
            this.GrapherPersonalID = GrapherPersonalID;
            this.GrapherMobileNumber = GrapherMobileNumber;
            this.GrapherSex = GrapherSex;
            this.ProvinceID = ProvinceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGrapherEarningRateProfileByGrapherIDandGrapherEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getGrapherEarningRateProfileByGrapherIDandGrapherEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long GrapherID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int EventTypeID;
        
        public getGrapherEarningRateProfileByGrapherIDandGrapherEmailRequest() {
        }
        
        public getGrapherEarningRateProfileByGrapherIDandGrapherEmailRequest(long GrapherID, int EventTypeID) {
            this.GrapherID = GrapherID;
            this.EventTypeID = EventTypeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGrapherEarningRateProfileByGrapherIDandGrapherEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getGrapherEarningRateProfileByGrapherIDandGrapherEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool getGrapherEarningRateProfileByGrapherIDandGrapherEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public double MorningRate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public double AfternoonRate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public double EveningRate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public double FulldayRate;
        
        public getGrapherEarningRateProfileByGrapherIDandGrapherEmailResponse() {
        }
        
        public getGrapherEarningRateProfileByGrapherIDandGrapherEmailResponse(bool getGrapherEarningRateProfileByGrapherIDandGrapherEmailResult, string errMsg, double MorningRate, double AfternoonRate, double EveningRate, double FulldayRate) {
            this.getGrapherEarningRateProfileByGrapherIDandGrapherEmailResult = getGrapherEarningRateProfileByGrapherIDandGrapherEmailResult;
            this.errMsg = errMsg;
            this.MorningRate = MorningRate;
            this.AfternoonRate = AfternoonRate;
            this.EveningRate = EveningRate;
            this.FulldayRate = FulldayRate;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : CameRoomWeb.CameRoomService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<CameRoomWeb.CameRoomService.IService>, CameRoomWeb.CameRoomService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CameRoomWeb.CameRoomService.GetDataResponse CameRoomWeb.CameRoomService.IService.GetData(CameRoomWeb.CameRoomService.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public string GetData(int value) {
            CameRoomWeb.CameRoomService.GetDataRequest inValue = new CameRoomWeb.CameRoomService.GetDataRequest();
            inValue.value = value;
            CameRoomWeb.CameRoomService.GetDataResponse retVal = ((CameRoomWeb.CameRoomService.IService)(this)).GetData(inValue);
            return retVal.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.GetDataResponse> CameRoomWeb.CameRoomService.IService.GetDataAsync(CameRoomWeb.CameRoomService.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.GetDataResponse> GetDataAsync(int value) {
            CameRoomWeb.CameRoomService.GetDataRequest inValue = new CameRoomWeb.CameRoomService.GetDataRequest();
            inValue.value = value;
            return ((CameRoomWeb.CameRoomService.IService)(this)).GetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CameRoomWeb.CameRoomService.GetDataUsingDataContractResponse CameRoomWeb.CameRoomService.IService.GetDataUsingDataContract(CameRoomWeb.CameRoomService.GetDataUsingDataContractRequest request) {
            return base.Channel.GetDataUsingDataContract(request);
        }
        
        public CameRoomWeb.CameRoomService.CompositeType GetDataUsingDataContract(CameRoomWeb.CameRoomService.CompositeType composite) {
            CameRoomWeb.CameRoomService.GetDataUsingDataContractRequest inValue = new CameRoomWeb.CameRoomService.GetDataUsingDataContractRequest();
            inValue.composite = composite;
            CameRoomWeb.CameRoomService.GetDataUsingDataContractResponse retVal = ((CameRoomWeb.CameRoomService.IService)(this)).GetDataUsingDataContract(inValue);
            return retVal.GetDataUsingDataContractResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.GetDataUsingDataContractResponse> CameRoomWeb.CameRoomService.IService.GetDataUsingDataContractAsync(CameRoomWeb.CameRoomService.GetDataUsingDataContractRequest request) {
            return base.Channel.GetDataUsingDataContractAsync(request);
        }
        
        public System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(CameRoomWeb.CameRoomService.CompositeType composite) {
            CameRoomWeb.CameRoomService.GetDataUsingDataContractRequest inValue = new CameRoomWeb.CameRoomService.GetDataUsingDataContractRequest();
            inValue.composite = composite;
            return ((CameRoomWeb.CameRoomService.IService)(this)).GetDataUsingDataContractAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CameRoomWeb.CameRoomService.getProvinceListResponse CameRoomWeb.CameRoomService.IService.getProvinceList(CameRoomWeb.CameRoomService.getProvinceListRequest request) {
            return base.Channel.getProvinceList(request);
        }
        
        public bool getProvinceList(out System.Data.DataSet ds, out string errMsg) {
            CameRoomWeb.CameRoomService.getProvinceListRequest inValue = new CameRoomWeb.CameRoomService.getProvinceListRequest();
            CameRoomWeb.CameRoomService.getProvinceListResponse retVal = ((CameRoomWeb.CameRoomService.IService)(this)).getProvinceList(inValue);
            ds = retVal.ds;
            errMsg = retVal.errMsg;
            return retVal.getProvinceListResult;
        }
        
        public System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.getProvinceListResponse> getProvinceListAsync(CameRoomWeb.CameRoomService.getProvinceListRequest request) {
            return base.Channel.getProvinceListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CameRoomWeb.CameRoomService.getPlaceListByProvinceIDResponse CameRoomWeb.CameRoomService.IService.getPlaceListByProvinceID(CameRoomWeb.CameRoomService.getPlaceListByProvinceIDRequest request) {
            return base.Channel.getPlaceListByProvinceID(request);
        }
        
        public bool getPlaceListByProvinceID(int provinceID, out System.Data.DataSet ds, out string errMsg) {
            CameRoomWeb.CameRoomService.getPlaceListByProvinceIDRequest inValue = new CameRoomWeb.CameRoomService.getPlaceListByProvinceIDRequest();
            inValue.provinceID = provinceID;
            CameRoomWeb.CameRoomService.getPlaceListByProvinceIDResponse retVal = ((CameRoomWeb.CameRoomService.IService)(this)).getPlaceListByProvinceID(inValue);
            ds = retVal.ds;
            errMsg = retVal.errMsg;
            return retVal.getPlaceListByProvinceIDResult;
        }
        
        public System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.getPlaceListByProvinceIDResponse> getPlaceListByProvinceIDAsync(CameRoomWeb.CameRoomService.getPlaceListByProvinceIDRequest request) {
            return base.Channel.getPlaceListByProvinceIDAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CameRoomWeb.CameRoomService.insertGrapherRegisterResponse CameRoomWeb.CameRoomService.IService.insertGrapherRegister(CameRoomWeb.CameRoomService.insertGrapherRegisterRequest request) {
            return base.Channel.insertGrapherRegister(request);
        }
        
        public bool insertGrapherRegister(string GrapherEmail, string GrapherName, string GrapherSurname, string GrapherPersonalID, byte[] GrapherPhoto, string GrapherMobileNumber, string GrapherSex, string Password, int ProvinceID, out string errMsg, out long GrapherID) {
            CameRoomWeb.CameRoomService.insertGrapherRegisterRequest inValue = new CameRoomWeb.CameRoomService.insertGrapherRegisterRequest();
            inValue.GrapherEmail = GrapherEmail;
            inValue.GrapherName = GrapherName;
            inValue.GrapherSurname = GrapherSurname;
            inValue.GrapherPersonalID = GrapherPersonalID;
            inValue.GrapherPhoto = GrapherPhoto;
            inValue.GrapherMobileNumber = GrapherMobileNumber;
            inValue.GrapherSex = GrapherSex;
            inValue.Password = Password;
            inValue.ProvinceID = ProvinceID;
            CameRoomWeb.CameRoomService.insertGrapherRegisterResponse retVal = ((CameRoomWeb.CameRoomService.IService)(this)).insertGrapherRegister(inValue);
            errMsg = retVal.errMsg;
            GrapherID = retVal.GrapherID;
            return retVal.insertGrapherRegisterResult;
        }
        
        public System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.insertGrapherRegisterResponse> insertGrapherRegisterAsync(CameRoomWeb.CameRoomService.insertGrapherRegisterRequest request) {
            return base.Channel.insertGrapherRegisterAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CameRoomWeb.CameRoomService.insertGrapherRegisterMapEarningRateResponse CameRoomWeb.CameRoomService.IService.insertGrapherRegisterMapEarningRate(CameRoomWeb.CameRoomService.insertGrapherRegisterMapEarningRateRequest request) {
            return base.Channel.insertGrapherRegisterMapEarningRate(request);
        }
        
        public bool insertGrapherRegisterMapEarningRate(long GrapherID, int EventTypeID, double MorningRate, double AfternoonRate, double EveningRate, double FullDayRate, out string errMsg) {
            CameRoomWeb.CameRoomService.insertGrapherRegisterMapEarningRateRequest inValue = new CameRoomWeb.CameRoomService.insertGrapherRegisterMapEarningRateRequest();
            inValue.GrapherID = GrapherID;
            inValue.EventTypeID = EventTypeID;
            inValue.MorningRate = MorningRate;
            inValue.AfternoonRate = AfternoonRate;
            inValue.EveningRate = EveningRate;
            inValue.FullDayRate = FullDayRate;
            CameRoomWeb.CameRoomService.insertGrapherRegisterMapEarningRateResponse retVal = ((CameRoomWeb.CameRoomService.IService)(this)).insertGrapherRegisterMapEarningRate(inValue);
            errMsg = retVal.errMsg;
            return retVal.insertGrapherRegisterMapEarningRateResult;
        }
        
        public System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.insertGrapherRegisterMapEarningRateResponse> insertGrapherRegisterMapEarningRateAsync(CameRoomWeb.CameRoomService.insertGrapherRegisterMapEarningRateRequest request) {
            return base.Channel.insertGrapherRegisterMapEarningRateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CameRoomWeb.CameRoomService.getGrapherProfileByEmailResponse CameRoomWeb.CameRoomService.IService.getGrapherProfileByEmail(CameRoomWeb.CameRoomService.getGrapherProfileByEmailRequest request) {
            return base.Channel.getGrapherProfileByEmail(request);
        }
        
        public bool getGrapherProfileByEmail(string GrapherEmail, out string errMsg, out long GrapherID, out string GrapherName, out string GrapherSurname, out string GrapherPersonalID, out string GrapherMobileNumber, out string GrapherSex, out int ProvinceID) {
            CameRoomWeb.CameRoomService.getGrapherProfileByEmailRequest inValue = new CameRoomWeb.CameRoomService.getGrapherProfileByEmailRequest();
            inValue.GrapherEmail = GrapherEmail;
            CameRoomWeb.CameRoomService.getGrapherProfileByEmailResponse retVal = ((CameRoomWeb.CameRoomService.IService)(this)).getGrapherProfileByEmail(inValue);
            errMsg = retVal.errMsg;
            GrapherID = retVal.GrapherID;
            GrapherName = retVal.GrapherName;
            GrapherSurname = retVal.GrapherSurname;
            GrapherPersonalID = retVal.GrapherPersonalID;
            GrapherMobileNumber = retVal.GrapherMobileNumber;
            GrapherSex = retVal.GrapherSex;
            ProvinceID = retVal.ProvinceID;
            return retVal.getGrapherProfileByEmailResult;
        }
        
        public System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.getGrapherProfileByEmailResponse> getGrapherProfileByEmailAsync(CameRoomWeb.CameRoomService.getGrapherProfileByEmailRequest request) {
            return base.Channel.getGrapherProfileByEmailAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CameRoomWeb.CameRoomService.getGrapherEarningRateProfileByGrapherIDandGrapherEmailResponse CameRoomWeb.CameRoomService.IService.getGrapherEarningRateProfileByGrapherIDandGrapherEmail(CameRoomWeb.CameRoomService.getGrapherEarningRateProfileByGrapherIDandGrapherEmailRequest request) {
            return base.Channel.getGrapherEarningRateProfileByGrapherIDandGrapherEmail(request);
        }
        
        public bool getGrapherEarningRateProfileByGrapherIDandGrapherEmail(long GrapherID, int EventTypeID, out string errMsg, out double MorningRate, out double AfternoonRate, out double EveningRate, out double FulldayRate) {
            CameRoomWeb.CameRoomService.getGrapherEarningRateProfileByGrapherIDandGrapherEmailRequest inValue = new CameRoomWeb.CameRoomService.getGrapherEarningRateProfileByGrapherIDandGrapherEmailRequest();
            inValue.GrapherID = GrapherID;
            inValue.EventTypeID = EventTypeID;
            CameRoomWeb.CameRoomService.getGrapherEarningRateProfileByGrapherIDandGrapherEmailResponse retVal = ((CameRoomWeb.CameRoomService.IService)(this)).getGrapherEarningRateProfileByGrapherIDandGrapherEmail(inValue);
            errMsg = retVal.errMsg;
            MorningRate = retVal.MorningRate;
            AfternoonRate = retVal.AfternoonRate;
            EveningRate = retVal.EveningRate;
            FulldayRate = retVal.FulldayRate;
            return retVal.getGrapherEarningRateProfileByGrapherIDandGrapherEmailResult;
        }
        
        public System.Threading.Tasks.Task<CameRoomWeb.CameRoomService.getGrapherEarningRateProfileByGrapherIDandGrapherEmailResponse> getGrapherEarningRateProfileByGrapherIDandGrapherEmailAsync(CameRoomWeb.CameRoomService.getGrapherEarningRateProfileByGrapherIDandGrapherEmailRequest request) {
            return base.Channel.getGrapherEarningRateProfileByGrapherIDandGrapherEmailAsync(request);
        }
    }
}
